### ISSUE TITLE
Update package on MOPS

### ISSUE THREAD

**Issue by tiagoicp** [usergeek/canistergeek-ic-motoko#6]
Hi,

On MOPS, the latest version is v0.0.4. 

Can you kindly update it to latest one there?
https://mops.one/canistergeek

![Screenshot 2023-11-30 at 23 40 48](https://github.com/usergeek/canistergeek-ic-motoko/assets/19423709/c2c08d7f-6f30-447e-b710-cffba3c0caa1)

**Comment by janusdotai** [comment]
bump

**Comment by alexeychirkov** [comment]
Sorry for the late answer.
Fresh version published.
